### ISSUE TITLE
Def.hashCode

### ISSUE THREAD

**Issue by paullepoulpe** [TiarkRompf/virtualization-lms-core#114]
I think I may have found something that could be a problem, please let me know if  something is wrong in my reasoning :

The lms framework performs CSE by reusing the same symbol every time the same Def element is reused in the same scope. 

The way it does that is through the hashcode method defined on Def: 

``` scala
abstract class Def[+T] { // operations (composite)
    override final lazy val hashCode = 
            scala.runtime.ScalaRunTime._hashCode(this.asInstanceOf[Product])
}
```

This is in turn forwarded to the following function (in [scala.util.hashing.MurmurHash3](https://github.com/scala/scala/blob/2.12.x/src/library/scala/util/hashing/MurmurHash3.scala#L52))

``` scala
/** Compute the hash of a product */
  final def productHash(x: Product, seed: Int): Int = {
    val arr = x.productArity
    // Case objects have the hashCode inlined directly into the
    // synthetic hashCode method, but this method should still give
    // a correct result if passed a case object.
    if (arr == 0) {
      x.productPrefix.hashCode
    }
    else {
      var h = seed
      var i = 0
      while (i < arr) {
        h = mix(h, x.productElement(i).##)
        i += 1
      }
      finalizeHash(h, arr)
    }
  }
```

As you can see, this function uses productPrefix to compute the hash only when the productArity is 0.

This means that the following 2 objects would end up having the same hash:

``` scala
scala> def hash (elem: Any) = {
     |   scala.runtime.ScalaRunTime._hashCode(elem.asInstanceOf[Product])
     | }
hash: (elem: Any)Int

scala> case class AddOne(i: Int) // extends Def[Int]
defined class AddOne

scala> case class RemoveOne(i: Int) // extends Def[Int]
defined class RemoveOne

scala> hash(AddOne(1)) == hash(RemoveOne(1))
res0: Boolean = true
```

Which in turn means that lms would transform a code that looks like this

``` scala
val x0 = 1
val x1 = AddOne(x0)
val x2 = RemoveOne(x0)
x2
```

into this:

``` scala
val x0 = 1
val x1 = AddOne(x0)
val x2 = x1
x2
```

**Comment by kjbrown** [comment]
Object equality is determined by method ‘equals’, not ‘hashCode’.

On Mar 18, 2016, at 12:56 AM, Damien Engels <notifications@github.com<mailto:notifications@github.com>> wrote:

I think I may have found something that could be a problem, please let me know if something is wrong in my reasoning :

The lms framework performs CSE by reusing the same symbol every time the same Def element is reused in the same scope.

The way it does that is through the hashcode method defined on Def:

abstract class Def[+T] { // operations (composite)
    override final lazy val hashCode =
            scala.runtime.ScalaRunTime._hashCode(this.asInstanceOf[Product])
}

This is in turn forwarded to the following function (in scala.util.hashing.MurmurHash3https://github.com/scala/scala/blob/2.12.x/src/library/scala/util/hashing/MurmurHash3.scala#L52)

/*\* Compute the hash of a product */
  final def productHash(x: Product, seed: Int): Int = {
    val arr = x.productArity
    // Case objects have the hashCode inlined directly into the
    // synthetic hashCode method, but this method should still give
    // a correct result if passed a case object.
    if (arr == 0) {
      x.productPrefix.hashCode
    }
    else {
      var h = seed
      var i = 0
      while (i < arr) {
        h = mix(h, x.productElement(i).##)
        i += 1
      }
      finalizeHash(h, arr)
    }
  }

As you can see, this function uses productPrefix to compute the hash only when the productArity is 0.

This means that the following 2 objects would end up having the same hash:

scala> def hash (elem: Any) = {
     |   scala.runtime.ScalaRunTime._hashCode(elem.asInstanceOf[Product])
     | }
hash: (elem: Any)Int

scala> case class AddOne(i: Int) // extends Def[Int]
defined class AddOne

scala> case class RemoveOne(i: Int) // extends Def[Int]
defined class RemoveOne

scala> hash(AddOne(1)) == hash(RemoveOne(1))
res0: Boolean = true

Which in turn means that lms would transform a code that looks like this

val x0 = 1
val x1 = AddOne(x0)
val x2 = RemoveOne(x0)
x2

into this:

val x0 = 1
val x1 = AddOne(x0)
val x2 = x1
x2

**Comment by TiarkRompf** [comment]
Closing this for now. Please re-open and post a testcase if this turns out to actually cause wrong behavior.
