### ISSUE TITLE
Add support for scala 2.12

### ISSUE THREAD

**Issue by igreenfield** [TiarkRompf/virtualization-lms-core#125]
Please add support for Scala 2.12

**Comment by TiarkRompf** [comment]
Done in branch develop-macrovirt-0.9.x. Use as follows in your build.sbt:

    resolvers += Resolver.sonatypeRepo("snapshots")
    libraryDependencies += "org.scala-lang.lms" %% "lms-core-macrovirt" % "0.9.0-SNAPSHOT"
