### ISSUE TITLE
CppHostTransfer Functions and a new data structure?

### ISSUE THREAD

**Issue by Qiyamah** [TiarkRompf/virtualization-lms-core#129]
Hi, 
I have implemented a new data structure which I would like to pass along and my code generation target is CPP.

I think I need to write my own transfer functions for that particular data structure.

emitMakeManifest,emitSend,emitRecv,emitSendView,emitRecvView,emitSendUpdate,emitRecvUpdate 

Can you tell me what each of these functions do? And where they are called and how they are called after compilation? 
A small example would suffice.

Thanks

**Comment by TiarkRompf** [comment]
The host transfer functions are for interacting with GPU code. If you're looking at plain CPP for CPU execution then you don't need to worry about these. Take a look at the C code generation logic in ArraysOps.scala to see how it works. You will most likely also need to override the "remap" function to print the correct name of your new type in C.
