### ISSUE TITLE
Tuples as structs

### ISSUE THREAD

**Issue by manojo** [TiarkRompf/virtualization-lms-core#54]
See https://github.com/manojo/lamp-dp-mt/blob/master/src/main/scala/lms/CGenTupleOps.scala for example/inspiration.

**Comment by asujeeth** [comment]
see also https://github.com/TiarkRompf/virtualization-lms-core/blob/wip-delite-develop/src/common/TupleOps.scala

**Comment by TiarkRompf** [comment]
i think this should be resolved as of aa4a4429e9722fcc45635df84f1833835d669ed9, which merged delite-develop into develop-0.4. if not please reopen.
