### ISSUE TITLE
Usage Based Optimising - Make the Common case fast

### ISSUE THREAD

**Issue by sirinath** [TiarkRompf/virtualization-lms-core#65]
Hi,

If I run a LMS programme with say 10k sets of test data can it be mate to optimise frequent use cases to be faster. 

A trivial example would auto allocating x capacity array list if say 75% of the cases this is enough. Perhaps you can add a window / slice / input set where you can produce multiple version for different input sets and produce the output for what was received in the last 30m or 10k iterations.

Also ability to input the threshold of cases to handle. This might be analogous to optimising a cost function over multiple iterations. Find the optimal code for given set of input cases.

This can be sent to LMS to Delite for better use cases.

Suminda

P.S. I am new to both these frameworks.

**Comment by TiarkRompf** [comment]
Thanks for your suggestions. Right now this seems to be discussion content, and I think the mailing lists would be a better place than the issue tracker.
