### ISSUE TITLE
Macro-trans into develop?

### ISSUE THREAD

**Issue by tzbob** [TiarkRompf/virtualization-lms-core#77]
I was wondering what was stopping the macro project to become the default LMS branch? It seems that a lot of work was done on decoupling LMS from Scala-Virtualized, basically saving it from deprecation and allowing it to run on 2.11, but it hasn't been merged into the 'main' branch yet?

Is there anything stopping this merge? Seems like the longer this gets dragged out the more of a pain it will be to merge it in between the other changes.

**Comment by TiarkRompf** [comment]
There are actually quite a few issues still to be sorted out. As you can see, large pieces of code are commented out in the macro branch. Here's a list of open issues: https://github.com/scala-lms/summer-of-lms-2014/blob/scala-virtualized/ISSUES.
