### ISSUE TITLE
Thesis link on web page broken

### ISSUE THREAD

**Issue by kodaj** [TiarkRompf/virtualization-lms-core#79]
Hi,

On http://scala-lms.github.io/resources.html, the "Tiark’s thesis" link (http://lampwww.epfl.ch/~rompf/thesis_120716.pdf) leads to a 403:

Forbidden

You don't have permission to access /~rompf/thesis_120716.pdf on this server.
Apache/2.4.7 (Ubuntu) Server at chara.epfl.ch Port 80

Regards,
Bence Kodaj

**Comment by TiarkRompf** [comment]
Fixed https://github.com/scala-lms/scala-lms.github.com/commit/be97b5633b37fa29cc7cdd72fcb2f8507f6a2a02
