### ISSUE TITLE
% is not a member of Rep[Long]

### ISSUE THREAD

**Issue by biboudis** [TiarkRompf/virtualization-lms-core#95]
We need to update `PrimitiveOps.scala`. I'll send a PR. ;)

**Comment by TiarkRompf** [comment]
still waiting on the PR :)

**Comment by TiarkRompf** [comment]
See #96. Done: https://github.com/TiarkRompf/virtualization-lms-core/commit/a0d847f44cdbe15e21b9be7bfbca955aeab7c99c
